//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : OnchariWycliffe
//" Script Date        : Mon Apr  8 19:15:23 2019
//" Generated By       : LoadRunner Recorder (Build: 971)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	return 0;
}

